project:
    application: tmall-springboot
    name: tmall-cms
    chineseName: tmall后台管理系统
    version:  TMALLCMS-V0.0.1
    unpackTime: 2018/4/16
    PIC: yaojiabin
    versionControlNo: TMALLCMS-V0.0.1
    versionControlPath: ssh://git@github.com:WarframePrimer/mytmallSpringBoot.git
    framework: springboot

beetl:
  templates-path: templates/
  config:
      html-tag-flag: true

spring:
    application:
        name: tmall-cms
    #HTTP字符编码配置
    http:
        encoding:
          charset: UTF-8
          force: true

    mvc:
      view:
        suffix: .html
#    ## jsp配置
#    mvc:
#        view:
#          prefix: /WEB-INF/page/
#          suffix: .jsp
#        date-format: yyyy-MM-dd HH:mm:ss
#    ## Freemarker 配置
#    freemarker:
#        ## 文件配置路径
#        template-loader-path: classpath:/templates/
#        cache: false
#        charset: UTF-8
#        check-template-location: true
#        content-type: text/html
#        expose-request-attributes: true
#        expose-session-attributes: true
#        request-context-attribute: request
#        suffix: .ftl

#    #thymeleaf 配置
#    thymeleaf:
#      mode: HTML5
#      cache: false
    ## 线程池 配置
    threadPool:
        corePoolSize: 20
        maxPoolSize: 400
        queueCapacity: 1000
        keepAliveSeconds: 300
    ## 数据源配置
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/tmall_springboot?characterEncoding=utf8
        username: root
        password: 123
        driverClassName: com.mysql.jdbc.Driver
        max-active: 500
        max-idle: 10000
        min-idle: 200
        initial-size: 50
    redis:
        host: 127.0.0.1
        port: 6379
        timeout: 5000

#mybatis配置:
mybatis:
    mapper-locations: com.warframe.tmall.repository/*.xml

server:
  # 端口
  port: 8071
  # 上下文路径
  context-path: /tmall-cms
#图片文件上传下载
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 106.15.231.173:22122

fdfs:
  soTimeout: 1500
  connectTimeout: 600
  resHost: 106.15.231.173
  storagePort: 8088
#  thumbImage:             #缩略图生成参数
#    width: 150
#    height: 150
  trackerList: 106.15.231.173:22122            #TrackerList参数,支持多个


redis:
  password:

#rediskey配置
redisKey:
  expire_time:
  prefix:
    cart_info_profix:
    redis_cart_expire_time:
    item_info_profix:
    item_info_base_suffix:
    cart_order_info_profix:
    cart_order_index_profix:
    index_ad:
    user_session:
    verifycode:
    mobile_login_code:
  suffix:
    item_info_base_suffix:
    item_info_desc_suffix:

login:
  random_number:
  success_url:
  validation:
    ismobileengaged:
    isemailengaged:
    ispinengaged:




